// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UNET.Data;

#nullable disable

namespace UNET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907231726_SeedCatalogoYRolAdministrador")]
    partial class SeedCatalogoYRolAdministrador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PermisoSobreRecursoRol", b =>
                {
                    b.Property<Guid>("PermisosSobreRecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermisosSobreRecursoId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolPermisosSobreRecurso", (string)null);

                    b.HasData(
                        new
                        {
                            PermisosSobreRecursoId = new Guid("6f1a1f2a-0000-4000-8000-000000000003"),
                            RolesId = new Guid("6f1a1f2a-0000-4000-8000-000000000004")
                        },
                        new
                        {
                            PermisosSobreRecursoId = new Guid("6f1a1f2a-0000-4000-8000-000000000009"),
                            RolesId = new Guid("6f1a1f2a-0000-4000-8000-000000000004")
                        },
                        new
                        {
                            PermisosSobreRecursoId = new Guid("6f1a1f2a-0000-4000-8000-00000000000a"),
                            RolesId = new Guid("6f1a1f2a-0000-4000-8000-000000000004")
                        },
                        new
                        {
                            PermisosSobreRecursoId = new Guid("6f1a1f2a-0000-4000-8000-00000000000b"),
                            RolesId = new Guid("6f1a1f2a-0000-4000-8000-000000000004")
                        });
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuariosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuarioRoles", (string)null);

                    b.HasData(
                        new
                        {
                            RolesId = new Guid("6f1a1f2a-0000-4000-8000-000000000004"),
                            UsuariosId = new Guid("6f1a1f2a-0000-4000-8000-000000000005")
                        });
                });

            modelBuilder.Entity("UNET.Data.Entities.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-000000000002"),
                            Nombre = "Ver"
                        },
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-000000000006"),
                            Nombre = "Crear"
                        },
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-000000000007"),
                            Nombre = "Editar"
                        },
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-000000000008"),
                            Nombre = "Eliminar"
                        });
                });

            modelBuilder.Entity("UNET.Data.Entities.PermisoSobreRecurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("PermisoId");

                    b.HasIndex("RecursoId");

                    b.ToTable("PermisosSobreRecurso");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-000000000003"),
                            Nombre = "ver_roles",
                            PermisoId = new Guid("6f1a1f2a-0000-4000-8000-000000000002"),
                            RecursoId = new Guid("6f1a1f2a-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-000000000009"),
                            Nombre = "crear_roles",
                            PermisoId = new Guid("6f1a1f2a-0000-4000-8000-000000000006"),
                            RecursoId = new Guid("6f1a1f2a-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-00000000000a"),
                            Nombre = "editar_roles",
                            PermisoId = new Guid("6f1a1f2a-0000-4000-8000-000000000007"),
                            RecursoId = new Guid("6f1a1f2a-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-00000000000b"),
                            Nombre = "eliminar_roles",
                            PermisoId = new Guid("6f1a1f2a-0000-4000-8000-000000000008"),
                            RecursoId = new Guid("6f1a1f2a-0000-4000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("UNET.Data.Entities.Recurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Recursos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-000000000001"),
                            Nombre = "Roles",
                            Tipo = "Entidad"
                        });
                });

            modelBuilder.Entity("UNET.Data.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("[Eliminado] = 0");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-000000000004"),
                            Descripcion = "Rol con acceso total al sistema",
                            Eliminado = false,
                            Nombre = "Administrador"
                        });
                });

            modelBuilder.Entity("UNET.Data.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1a1f2a-0000-4000-8000-000000000005"),
                            Activo = true,
                            Email = "admin@unet.edu.ar",
                            Legajo = "0000",
                            PasswordHash = "$2a$11$PZLTd1lgBc/J9fbWUMAkXOzVu1sVgye9og5ozbsh.h/Xji2k1uhiK"
                        });
                });

            modelBuilder.Entity("PermisoSobreRecursoRol", b =>
                {
                    b.HasOne("UNET.Data.Entities.PermisoSobreRecurso", null)
                        .WithMany()
                        .HasForeignKey("PermisosSobreRecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNET.Data.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.HasOne("UNET.Data.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNET.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UNET.Data.Entities.PermisoSobreRecurso", b =>
                {
                    b.HasOne("UNET.Data.Entities.Permiso", "Permiso")
                        .WithMany("PermisosSobreRecurso")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNET.Data.Entities.Recurso", "Recurso")
                        .WithMany("PermisosSobreRecurso")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("UNET.Data.Entities.Permiso", b =>
                {
                    b.Navigation("PermisosSobreRecurso");
                });

            modelBuilder.Entity("UNET.Data.Entities.Recurso", b =>
                {
                    b.Navigation("PermisosSobreRecurso");
                });
#pragma warning restore 612, 618
        }
    }
}
